# Generated by Django 3.0.10 on 2020-12-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('door_number', models.CharField(max_length=255)),
                ('door_type', models.CharField(blank=True, max_length=255, null=True)),
                ('door_type_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_hw_lower', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_hw_upper', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_hw_backset', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_hw_lock_height_prep_lower', models.CharField(blank=True, max_length=255, null=True)),
                ('door_lock_hw_lock_height_prep_upper', models.CharField(blank=True, max_length=255, null=True)),
                ('door_closing_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('door_electrified_hw', models.CharField(blank=True, max_length=255, null=True)),
                ('door_type_fire', models.BooleanField(blank=True, default=False, null=True)),
                ('door_type_fire_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('door_type_window', models.CharField(blank=True, max_length=255, null=True)),
                ('door_type_window_measurement', models.CharField(blank=True, max_length=255, null=True)),
                ('door_handling', models.CharField(blank=True, max_length=255, null=True)),
                ('door_accessory', models.CharField(blank=True, max_length=255, null=True)),
                ('door_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('door_pic_out', models.BooleanField(default=False)),
                ('door_pic_in', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Doors',
            },
        ),
        migrations.CreateModel(
            name='DoorsProMas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('door_number', models.CharField(max_length=255)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('door_description', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('stage', models.CharField(blank=True, max_length=255, null=True)),
                ('lock_part_num', models.CharField(blank=True, max_length=255, null=True)),
                ('non_keyed', models.BooleanField(default=False)),
                ('height', models.CharField(max_length=255)),
                ('width', models.CharField(max_length=255)),
                ('thickness', models.CharField(max_length=255)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('diff_keying_side2', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('pinning_notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'DoorsProMas',
            },
        ),
        migrations.CreateModel(
            name='DPMCustomerDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_description', models.CharField(max_length=255)),
                ('file_number', models.CharField(max_length=255)),
                ('door_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DPMCustomerDesc',
            },
        ),
        migrations.CreateModel(
            name='Frames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('door_number', models.CharField(max_length=255)),
                ('gps', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_type', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_type_dimension', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_type_fire', models.BooleanField(blank=True, default=False, null=True)),
                ('frame_type_fire_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_strike_lower', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_strike_upper', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_hinge', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_hinge_m1', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_hinge_m2', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_hinge_m3', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_prep_hinge_m4', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Frames',
            },
        ),
        migrations.CreateModel(
            name='HwPictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('door_number', models.CharField(max_length=255)),
                ('door_pic_out', models.CharField(blank=True, max_length=255, null=True)),
                ('door_pic_in', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'HwPictures',
            },
        ),
        migrations.CreateModel(
            name='KeyingProMas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('door_number', models.CharField(max_length=255)),
                ('position_type', models.CharField(blank=True, max_length=255, null=True)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('key_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'KeyingProMas',
            },
        ),
        migrations.CreateModel(
            name='KeyQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(max_length=255)),
                ('key_id', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('key_description', models.CharField(blank=True, max_length=255, null=True)),
                ('key_above', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('part_code', models.CharField(blank=True, max_length=255, null=True)),
                ('stamping', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_separate', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
                ('replaced', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'KeyQty',
            },
        ),
        migrations.CreateModel(
            name='KeySequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=255, null=True)),
                ('key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('key_holder', models.CharField(blank=True, max_length=255, null=True)),
                ('tenant_location', models.CharField(blank=True, max_length=255, null=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('lost_key', models.BooleanField(blank=True, default=False, null=True)),
                ('broken_key', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'KeySequence',
            },
        ),
    ]
