# Generated by Django 3.0.10 on 2021-01-29 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_door_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('key_code', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('pickup', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
