# Generated by Django 3.0.10 on 2021-01-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0002_keyrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyrequest',
            old_name='pickup',
            new_name='pickup_by',
        ),
        migrations.RemoveField(
            model_name='keyrequest',
            name='key_type',
        ),
    ]
