# Generated by Django 3.0.10 on 2021-02-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0003_auto_20210129_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyRequest',
        ),
    ]
