# Generated by Django 3.0.10 on 2021-02-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0006_auto_20210206_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyrequestimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='key_request'),
        ),
    ]
