# Generated by Django 3.0.10 on 2021-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0008_auto_20210317_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyQtyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('keys', models.ManyToManyField(to='key_door_finder.KeyQty')),
            ],
            options={
                'db_table': 'KeyGroups',
            },
        ),
    ]
