# Generated by Django 3.0.10 on 2021-03-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0009_keyqtygroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyqtygroup',
            name='keys',
        ),
        migrations.AddField(
            model_name='keyqtygroup',
            name='keys_sequences',
            field=models.ManyToManyField(to='key_door_finder.KeySequence'),
        ),
    ]
