# Generated by Django 3.0.10 on 2021-03-25 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0010_auto_20210324_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyqtygroup',
            name='keys_sequences',
        ),
        migrations.AddField(
            model_name='keysequence',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='key_door_finder.KeyQtyGroup'),
        ),
    ]
