# Generated by Django 3.0.10 on 2021-03-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0011_auto_20210325_0812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeyQtyGroup',
            new_name='KeyGroup',
        ),
    ]
