# Generated by Django 3.0.10 on 2021-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0012_auto_20210325_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='keygroup',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
