# Generated by Django 3.0.10 on 2021-04-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('key_door_finder', '0013_keygroup_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyAuditReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('audit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('audit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('confirm', models.BooleanField(blank=True, default=False, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
