# Generated by Django 3.0.10 on 2021-04-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_door_finder', '0014_keyauditreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyauditreport',
            name='audit_id',
        ),
        migrations.AddField(
            model_name='keysequence',
            name='audit_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='key_door_finder.KeyAuditReport'),
        ),
    ]
