# Generated by Django 3.0.10 on 2021-01-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0006_auto_20210120_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='braintree_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
