# Generated by Django 3.0.10 on 2021-01-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0007_user_braintree_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='braintree_client_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
