# Generated by Django 3.0.10 on 2021-01-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0008_user_braintree_client_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='braintree_client_token',
        ),
    ]
