# Generated by Django 3.0.10 on 2021-02-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0011_transaction_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_for',
            field=models.CharField(default='invoice', max_length=255),
            preserve_default=False,
        ),
    ]
