# Generated by Django 3.0.10 on 2021-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0013_auto_20210201_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bt_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
