# Generated by Django 3.0.10 on 2021-02-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0014_transaction_bt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
