# Generated by Django 3.0.10 on 2021-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0015_auto_20210208_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenumber',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
